language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - docker
before_install:
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
deploy:
  - provider: script
    script: ./push_to_hub_travis.sh
    on:
      all_branches: true
