language: java
jdk:
- oraclejdk8
sudo: false
script: mvn package
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file_glob: true
  file: '/home/travis/build/DD-DeCaF/ice/target/ice-*.war'
  skip_cleanup: true
  on:
    repo: DD-DeCaF/ice
