language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - docker
before_install:
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
deploy:
  - provider: releases
    script: mvn package
    api_key:
      secure: $API_KEY
    file_glob: true
    file: '/home/travis/build/DD-DeCaF/ice/target/ice-*.war'
    skip_cleanup: true
    on:
      repo: DD-DeCaF/ice
  - provider: script
    script: ./push_to_hub_travis.sh
    on:
      all_branches: true
