version: '2'

services:
    web:
        build: .
        ports:
            - 8080:8080
            - 8443:8443
        depends_on:
            - db

    db:
        image: postgres:latest
        hostname: db
        container_name: db
        environment:
            - POSTGRES_USER=ice
            - POSTGRES_DB=icedb
